# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e002df9ef571ca12ff6502b7c5fc436af43e827c0b6f3b1f9192c8e3cb639f4c5421c2a1d91bdb26b3fab1ede4dac32c2dc097e23aaa3b8ff316e9c4579271

test:
  secret_key_base: 07748ff899ca974f84fd6126c07d786b9fa821406d64a3be5eff58330a52a6a11b86baf283e4ca6dc27b2a132ecd65f81b2f0c5eeee23f316f671530192c3a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
